repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.9.5
     hooks:
        - id: ruff  # Linter
          args: [--fix]  # Ensure fixes are applied
          files: ^lab1/laboratory/src
        - id: ruff-format  # Formatter
          files: ^lab1/laboratory/src

   - repo: https://github.com/rubik/xenon
     rev: v0.9.0
     hooks:
     - id: xenon
       args: ['--max-absolute=B']
       files: ^lab1/laboratory/src