[project]
name = "laboratory"
version = "0.1.0"
description = "Lab1 warm-up task"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.3.0",
    "pyaml>=25.7.0",
    "pydantic-settings>=2.11.0",
]
