
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5555:5432"
    volumes:
      - ./init_db/prepare_similarity_search_service_db.sql:/docker-entrypoint-initdb.d/prepare_similarity_search_service_db.sql