FROM python:3.12-slim

RUN pip install --no-cache-dir fastapi uvicorn onnxruntime numpy

WORKDIR /app
COPY onnx_api.py .
COPY models/model.onnx ./models/model.onnx
COPY models/model.onnx.data ./models/model.onnx.data

CMD ["uvicorn", "onnx_api:app", "--host", "0.0.0.0", "--port", "8000"]